debug: false # logback, Spring Boot의 각종 debug 로그는 일단은 뜨지 않게
management:
  endpoints:
    web:
      exposure:
        include: "*" # 액추에이터의 엔드포인트 중 감춰져 있는 것을 모두 활성화

logging:
  level:
    com.fastcampus.projectboard: debug # 구체적으로 보고 싶은 로그 레벨 - 적용 패키지 명시
    org.springframework.web.servlet: debug # request, response 로그 관련
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA 쿼리 로그는 debug 로그이나, 어떤 파라미터인지까지 보려면 trace 필요

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: crossjoinAdmin
    password: thisisTESTpw!#%&
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8 버전 이상은 cj 패키지 붙은 것 사용
    # H2 DB In-memory 사용하는 경우의 설정
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true # 테스트용 데이터베이스 데이터 생성 가능 # resources 안에 sql 파일 만들어서 초기 데이터 세팅
    hibernate:
      ddl-auto: create # 엔티티를 통해 DDL을 자동으로 작성하여 테이블을 생성
    show-sql: true # SQL 쿼리문 보기
    properties: # 추가적인 프로퍼티로 JPA에 사용할 구현체에 종속된 프로퍼티 설정
      hibernate.format_sql: true # SQL문을 예쁘게 포매팅
      hibernate.default_batch_fetch_size: 100 # n+1 쿼리 문제 관련, 최대 100개 단위로 묶어서 벌크로 select할 수 있도록
#  h2: # 테스트용 H2 DB 웹 콘솔은 안 쓰기
#    console:
#      enabled: false
      # 사용하는 경우 datasource url은 jdbc:h2:mem:testdb로 설정, username, driver class 설정
      # http://localhost:[포트번호]/h2-console/로 접속, JDBC URL에 위 jdbc:h2:mem:testdb 입력
  sql:
    init:
      mode: always # resources의 data.sql을 항상 작동하게 # 배포 전 개발 기간에는 always로 해서 계속 테스트 데이터 들어가도록 만듦
  data:
    rest:
      base-path: /api # localhost:8080/api로 접속 시 HAL Explorer 볼 수 있음 - Data REST로 생성된 restful API 확인 가능 
      detection-strategy: annotated # spring data REST doc 참고

#---
# yaml 파일은 ---을 기준으로 document가 나뉨, document별로 Spring의 다른 Profile 설정하여 사용 가능
# 테스트 DB 사용 프로파일
#spring:
#  config:
#    activate: # cf. 예전에는 spring.profiles.active였으나, 지금은 완전히 빠짐
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none
